name: auto merge
on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'automation')
    steps:
      - if: contains(github.event.pull_request.labels.*.name, 'cargo check')
        name: Cargo check
        run: nix develop -c bash -c "cd test-runner && cargo check"

      - name: Auto-merge for PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

