name: build on push

on: [ push, pull_request ]

jobs:
  buildUnityGames:
    name: build unity game ${{ matrix.targetGame.path }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetGame:
          - path: 2022.3.41f1-base
            targetPlatform: StandaloneLinux64
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/cache@v4
        with:
          path: ${{ matrix.targetGame.path }}/Library
          key: Library-${{ hashFiles('${{ matrix.targetGame.path }}/Assets/**', '${{ matrix.targetGame.path }}/Packages/**', '${{ matrix.targetGame.path }}/ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetGame.targetPlatform }}
          projectPath: ${{ matrix.targetGame.path }}
          buildsPath: ${{ matrix.targetGame.path }}/build
          buildName: build

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.targetGame.path }}
          path: ${{ matrix.targetGame.path }}/build/${{ matrix.targetGame.targetPlatform }}
  buildTestRunnerLinux:
    name: build test runner for linux
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: test-runner -> test-runner

      - name: build release
        run: nix build .\#test-runner

      - name: get built artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-runner-unix
          path: result/bin/test-runner
  buildTestRunnerWindows:
    name: build test runner for windows
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: rustup toolchain install
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: test-runner -> test-runner

      - name: build release
        run: cargo build --release
        working-directory: test-runner

      - name: get built artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-runner-win
          path: test-runner/target/release/test-runner.exe
